# Generated by Django 5.2.5 on 2025-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pictures/avatar_cat.png', null=True, upload_to='profile_pictures/', verbose_name='プロフィール画像'),
        ),
    ]
