# Generated by Django 5.2.6 on 2025-09-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_level',
            field=models.PositiveIntegerField(default=1, help_text='1〜5の運動レベル', verbose_name='運動レベル'),
        ),
    ]
