# Generated by Django 5.2.6 on 2025-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
