# Generated by Django 5.2.6 on 2025-09-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_status_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_level',
            field=models.PositiveIntegerField(default=1, help_text='1〜5の運動レベル', verbose_name='運動レベル'),
        ),
    ]
