# Generated by Django 5.2.5 on 2025-08-29 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'お問い合わせメッセージ',
                'verbose_name_plural': 'お問い合わせメッセージ',
            },
        ),
    ]
