# Generated by Django 5.2.6 on 2025-09-27 02:34

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        if not post.slug or post.slug.strip() == "":
            base_slug = slugify(post.title) if post.title else f'post-{post.pk}'
            slug_candidate = base_slug
            counter = 1
            while Post.objects.filter(slug=slug_candidate).exclude(pk=post.pk).exists():
                slug_candidate = f"{base_slug}-{counter}"
                counter += 1
            post.slug = slug_candidate
            post.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),  # 直前のマイグレーションファイル名に置き換え
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
