# Generated by Django 5.2.5 on 2025-09-09 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_alter_follow_options_alter_follow_follower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_set', to=settings.AUTH_USER_MODEL, verbose_name='ブロックされるユーザー')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_set', to=settings.AUTH_USER_MODEL, verbose_name='ブロックするユーザー')),
            ],
            options={
                'verbose_name': 'ブロック',
                'verbose_name_plural': 'ブロック',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
